name: Terminal Press
favicon: null
layout_spectrum: 0.3846879289485514
typography_spectrum: 0.8839604465756565
title: Virtual Reality - Video Games - Apps - Comic Books  - Graphic Novels
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8489061978179961
  lightness: 0.769762942334637
  saturation: 0.00872488971799612
  rhythmicContrast: 0.30299778771586716
purpose: []
